# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5b5b7bfe09d46fe0022230f2d32be9d185d016ac3048e9fdb89750948bc728215fc22c72a2e574a8960231776b00e10c0ea078833b15888db221262f445d8dd

test:
  secret_key_base: 4613dffaa23ee76de4cdb650c5398c745eaaf9f2f79da095d251c6fcbcc110d964c9e9d76340a58012df497b4efade11e3bca5f24bbce15532fd2c3553dd0de1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
